# スプレッドシートの情報をContentfulにアップロード
name: deployMasterByAmplify
on: [workflow_dispatch]
env:
  PICKER_AMPLIFY_DEPLOY_WEBHOOK_URL_MASTER: ${{secrets.PICKER_AMPLIFY_DEPLOY_WEBHOOK_URL_MASTER}}
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./track-and-field"
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm i
      - run: npm run deployMasterByAmplify
